1.This problem set is based on lectures 4,5 and 6. For a complete list of topics please
consult page 2 of the course syllabus. Please consult the “Instructions for Problem
Set Submissions” document under course information before submitting your
assignment.
Question 1
Consider the following Python module:
a = 0
def b():
 global a
 a = c(a)
def c(a):
 return a + 2
After importing the module into the interpreter, you execute:
>>> b()
>>> b()
>>> b()
>>> a
?
What value is displayed when the last expression (a) is evaluated? Explain your
answer by indicating what happens in every executed statement.

In [ ]:
a = 0

def b():
    global a
    a = c(a)

def c(a):
    return a + 2

# Execute the b() function three times
b()
b()
b()

# Check the value of a
a

In [ ]:
2.Function fileLength(), given to you, takes the name of a file as input and returns
the length of the file:
>>> fileLength('midterm.py')
284
>>> fileLength('idterm.py')
Traceback (most recent call last):
File "<pyshell#34>", line 1, in <module>
 fileLength('idterm.py')
File "/Users/me/midterm.py", line 3, in fileLength
 infile = open(filename)
FileNotFoundError: [Errno 2] No such file or directory:
'idterm.py'
As shown above, if the file cannot be found by the interpreter or if it cannot be read
as a text file, an exception will be raised. Modify function fileLength() so that a
friendly message is printed instead:
>>> fileLength('midterm.py')
358
>>> fileLength('idterm.py')
File idterm.py not found.

In [ ]:
def fileLength(filename):
    try:
        infile = open(filename, 'r')
        content = infile.read()
        infile.close()
        return len(content)
    except FileNotFoundError:
        return f"File {filename} not found."

# Example usages
print(fileLength('midterm.py'))
print(fileLength('idterm.py'))

In [ ]:
3. Write a class named Marsupial that can be used as shown below:
>>> m = Marsupial()
>>> m.put_in_pouch('doll')
>>> m.put_in_pouch('firetruck')
>>> m.put_in_pouch('kitten')
>>> m.pouch_contents()
['doll', 'firetruck', 'kitten']                                                                                                                                                   Now write a class named Kangaroo as a subclass of Marsupial that inherits all the
attributes of Marsupial and also:
a. extends the Marsupial __init__ constructor to take, as input, the
coordinates x and y of the Kangaroo object,
b. supports method jump that takes number values dx and dy as input and
moves the kangaroo by dx units along the x-axis and by dy units along the yaxis, and
c. overloads the __str__ operator so it behaves as shown below.
>>> k = Kangaroo(0,0)
>>> print(k)
I am a Kangaroo located at coordinates (0,0)
>>> k.put_in_pouch('doll')
>>> k.put_in_pouch('firetruck')
>>> k.put_in_pouch('kitten')
>>> k.pouch_contents()
['doll', 'firetruck', 'kitten']
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> print(k)
I am a Kangaroo located at coordinates (3,0)

In [ ]:
class Marsupial:
    def __init__(self):
        self.pouch = []

    def put_in_pouch(self, item):
        self.pouch.append(item)

    def pouch_contents(self):
        return self.pouch


class Kangaroo(Marsupial):
    def __init__(self, x, y):
        super().__init__()
        self.x = x
        self.y = y

    def jump(self, dx, dy):
        self.x += dx
        self.y += dy

    def __str__(self):
        return f"I am a Kangaroo located at coordinates ({self.x},{self.y})"

# Usage
m = Marsupial()
m.put_in_pouch('doll')
m.put_in_pouch('firetruck')
m.put_in_pouch('kitten')
print(m.pouch_contents())

k = Kangaroo(0, 0)
print(k)
k.put_in_pouch('doll')
k.put_in_pouch('firetruck')
k.put_in_pouch('kitten')
print(k.pouch_contents())

k.jump(1, 0)
k.jump(1, 0)
k.jump(1, 0)
print(k)

In [ ]:
4. Write function collatz() that takes a positive integer x as input and prints the
Collatz sequence starting at x. A Collatz sequence is obtained by repeatedly applying
this rule to the previous number x in the sequence:
x = {
𝑥/2 𝑖𝑓 𝑥 𝑖𝑠 𝑒𝑣𝑒𝑛
3𝑥 + 1 𝑖𝑓 𝑥 𝑖𝑠 𝑜𝑑𝑑
Your function should stop when the sequence gets to number 1. Your
implementation must be recursive, without any loops.                                                                                           >>> collatz(1)
1
>>> collatz(10)
10
5
16
8
4
2
1

In [ ]:
def collatz(x):
    print(x)
    if x == 1:
        return
    elif x % 2 == 0:
        collatz(x // 2)
    else:
        collatz(3 * x + 1)

# Test the function with examples
collatz(1)
collatz(10)

In [ ]:
5. Write a recursive method binary() that takes a non-negative
integer n and prints the binary representation of integer n.
>>> binary(0)
0
>>> binary(1)
1
>>> binary(3)
11
>>> binary(9)
1001

In [ ]:
def binary(n):
    if n > 1:
        binary(n // 2)
    print(n % 2, end='')

# Test the function with examples
binary(0)
print()  # Print a newline to separate results
binary(1)
print()
binary(3)
print()
binary(9)

In [ ]:
6. Implement a class named HeadingParser that can be used to parse an HTML
document, and retrieve and print all the headings in the document. You should
implement your class as a subclass of HTMLParser, defined in Standard Library
module html.parser. When fed a string containing HTML code, your class should
print the headings, one per line and in the order in which they appear in the
document. Each heading should be indented as follows: an h1 heading should have                                     indentation 0, and h2 heading should have indentation 1, etc. Test your
implementation using w3c.html.
>>> infile = open('w3c.html')
>>> content = infile.read()
>>> infile.close()
>>> hp = HeadingParser()
>>> hp.feed(content)
W3C Mission
Principles

In [ ]:
from html.parser import HTMLParser
class HeadingParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_heading = False
        self.indentation = 0

    def handle_starttag(self, tag, attrs):
        if tag.startswith("h") and tag[1:].isdigit():
            self.in_heading = True
            self.indentation = int(tag[1]) - 1

    def handle_data(self, data):
        if self.in_heading:
            print(" " * self.indentation + data)

    def handle_endtag(self, tag):
        if self.in_heading:
            self.in_heading = False
infile = open('w3c.html')
content = infile.read()
infile.close()

hp = HeadingParser()
hp.feed(content)
from html.parser import HTMLParser

class HeadingParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_heading = False
        self.indentation = 0

    def handle_starttag(self, tag, attrs):
        if tag.startswith("h") and tag[1:].isdigit():
            self.in_heading = True
            self.indentation = int(tag[1]) - 1

    def handle_data(self, data):
        if self.in_heading:
            print(" " * self.indentation + data)

    def handle_endtag(self, tag):
        if self.in_heading:
            self.in_heading = False

infile = open('w3c.html')
content = infile.read()
infile.close()

hp = HeadingParser()
hp.feed(content)

In [ ]:
7. Implement recursive function webdir() that takes as input: a URL (as a string) and
non-negative integers depth and indent. Your function should visit every web
page reachable from the starting URL web page in depth clicks or less, and print
each web page's URL. As shown below, indentation, specified by indent, should
be used to indicate the depth of a URL.
>>>
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html'
, 2, 0)
http://reed.cs.depaul.edu/lperkovic/csc242/test1.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test2.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test3.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html

In [ ]:
import requests
from bs4 import BeautifulSoup

def webdir(url, depth, indent):
    if depth < 0:
        return
    try:
        response = requests.get(url)
        response.raise_for_status()
    except requests.exceptions.RequestException:
        return

    soup = BeautifulSoup(response.text, 'html.parser')
    print(" " * indent + url)

    if depth > 0:
        links = soup.find_all('a')
        for link in links:
            href = link.get('href')
            if href and href.startswith('http'):
                webdir(href, depth - 1, indent + 1)

# Usage example
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html', 2, 0)

In [ ]:
8. Write SQL queries on the below database table that return:
a) All the temperature data.
b) All the cities, but without repetition.
c) All the records for India.
d) All the Fall records.                                                                                                                                                                       e) The city, country, and season for which the average rainfall is between 200
and 400 millimeters.
f) The city and country for which the average Fall temperature is above 20
degrees, in increasing temperature order.
g) The total annual rainfall for Cairo.
h) The total rainfall for each season.
City Country Season Temperature
(C)
Rainfall
(mm)
Mumbai India Winter 24.8 5.9
Mumbai India Spring 28.4 16.2
Mumbai India Summer 27.9 1549.4
Mumbai India Fall 27.6 346.0
London United Kingdom Winter 4.2 207.7
London United Kingdom Spring 8.3 169.6
London United Kingdom Summer 15.7 157.0
London United Kingdom Fall 10.4 218.5
Cairo Egypt Winter 13.6 16.5
Cairo Egypt Spring 20.7 6.5
Cairo Egypt Summer 27.7 0.1
Cairo Egypt Fall 22.2 4.5

In [ ]:
import sqlite3

# Create a SQLite database in memory and connect to it
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create a table and insert the provided data
cursor.execute('''
CREATE TABLE Weather (
    City TEXT,
    Country TEXT,
    Season TEXT,
    Temperature REAL,
    Rainfall REAL
);
''')

data = [
    ('Mumbai', 'India', 'Winter', 24.8, 5.9),
    ('Mumbai', 'India', 'Spring', 28.4, 16.2),
    ('Mumbai', 'India', 'Summer', 27.9, 1549.4),
    ('Mumbai', 'India', 'Fall', 27.6, 346.0),
    ('London', 'United Kingdom', 'Winter', 4.2, 207.7),
    ('London', 'United Kingdom', 'Spring', 8.3, 169.6),
    ('London', 'United Kingdom', 'Summer', 15.7, 157.0),
    ('London', 'United Kingdom', 'Fall', 10.4, 218.5),
    ('Cairo', 'Egypt', 'Winter', 13.6, 16.5),
    ('Cairo', 'Egypt', 'Spring', 20.7, 6.5),
    ('Cairo', 'Egypt', 'Summer', 27.7, 0.1),
    ('Cairo', 'Egypt', 'Fall', 22.2, 4.5),
]

cursor.executemany('INSERT INTO Weather VALUES (?, ?, ?, ?, ?);', data)

# Commit the changes
conn.commit()

# SQL queries
# a) All the temperature data.
temperature_query = "SELECT Temperature FROM Weather;"
temperature_data = cursor.execute(temperature_query).fetchall()
print("a) All the temperature data:")
print(temperature_data)

# b) All the cities, but without repetition.
cities_query = "SELECT DISTINCT City FROM Weather;"
cities = cursor.execute(cities_query).fetchall()
print("\nb) All the cities, but without repetition:")
print(cities)

# c) All the records for India.
india_records_query = "SELECT * FROM Weather WHERE Country = 'India';"
india_records = cursor.execute(india_records_query).fetchall()
print("\nc) All the records for India:")
print(india_records)

# d) All the Fall records.
fall_records_query = "SELECT * FROM Weather WHERE Season = 'Fall';"
fall_records = cursor.execute(fall_records_query).fetchall()
print("\nd) All the Fall records:")
print(fall_records)

# e) The city, country, and season for which the average rainfall is between 200 and 400 millimeters.
avg_rainfall_query = "SELECT City, Country, Season " \
                    "FROM Weather " \
                    "GROUP BY City, Country, Season " \
                    "HAVING AVG(Rainfall) BETWEEN 200 AND 400;"
avg_rainfall_records = cursor.execute(avg_rainfall_query).fetchall()
print("\ne) The city, country, and season for which the average rainfall is between 200 and 400 millimeters:")
print(avg_rainfall_records)

# f) The city and country for which the average Fall temperature is above 20 degrees, in increasing temperature order.
avg_fall_temperature_query = "SELECT City, Country " \
                           "FROM Weather " \
                           "WHERE Season = 'Fall' " \
                           "GROUP BY City, Country " \
                           "HAVING AVG(Temperature) > 20 " \
                           "ORDER BY AVG(Temperature) ASC;"
avg_fall_temperature_records = cursor.execute(avg_fall_temperature_query).fetchall()
print("\nf) The city and country for which the average Fall temperature is above 20 degrees, in increasing temperature order:")
print(avg_fall_temperature_records)

# g) The total annual rainfall for Cairo.
total_rainfall_cairo_query = "SELECT SUM(Rainfall) FROM Weather WHERE City = 'Cairo';"
total_rainfall_cairo = cursor.execute(total_rainfall_cairo_query).fetchone()[0]
print("\ng) The total annual rainfall for Cairo:")
print(total_rainfall_cairo)

# h) The total rainfall for each season.
total_rainfall_by_season_query = "SELECT Season, SUM(Rainfall) FROM Weather GROUP BY Season;"
total_rainfall_by_season = cursor.execute(total_rainfall_by_season_query).fetchall()
print("\nh) The total rainfall for each season:")
print(total_rainfall_by_season)

# Close the connection
conn.close()

In [ ]:
9. Suppose list words is defined as follows:
>>> words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over',
'the', 'lazy', 'dog']
Write list comprehension expressions that use list words and generate the following
lists:
a) ['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE',
'LAZY', 'DOG']
b) ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog']
c) [3, 5, 5, 3, 5, 4, 3, 4, 3] (the list of lengths of words in list
words).
d) [['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN',
'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5],
['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy',
4], ['DOG', 'dog', 3]] (the list containing a list for every word of list
words, where each list contains the word in uppercase and lowercase and the
length of the word.)
e) ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog'] (the list of words in list words containing 4 or more
characters.)

In [ ]:
words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

# a) Uppercase words
uppercase_words = [word.upper() for word in words]
print("a) Uppercase words:")
print(uppercase_words)

# b) Lowercase words
lowercase_words = [word.lower() for word in words]
print("\nb) Lowercase words:")
print(lowercase_words)

# c) List of word lengths
word_lengths = [len(word) for word in words]
print("\nc) List of word lengths:")
print(word_lengths)

# d) List of lists containing word in uppercase, lowercase, and length
word_info = [[word.upper(), word.lower(), len(word)] for word in words]
print("\nd) List of lists containing word in uppercase, lowercase, and length:")
print(word_info)

# e) Words with 4 or more characters
long_words = [word for word in words if len(word) >= 4]
print("\ne) Words with 4 or more characters:")
print(long_words)